### ISSUE TITLE
Fix 502 Bad Gateway in URL parameters

### ISSUE THREAD

**Issue by aloisdg** [ethel-dev/simplemark#6]
Hello,

I don't achieve to works with huge markdown in URL parameters.

For example, if I take the [dillinger](http://dillinger.io/)'s sample, I get a 502 Bad Gateway.
No problem with simple markdown like :

```
# toto
```

Cheers,

**Comment by ethel-dev** [comment]
Hey, would you mind specifying the URL you used with parameters that gave you this issue?

**Comment by aloisdg** [comment]
Sure! [here it is](http://ethanarterberry.com/Sexydown?code=true&val=%23%20Dillinger%0A%0ADillinger%20is%20a%20cloud-enabled%2C%20mobile-ready%2C%20offline-storage%2C%20AngularJS%20powered%20HTML5%20Markdown%20editor.%0A%0A%20%20-%20Type%20some%20Markdown%20on%20the%20left%0A%20%20-%20See%20HTML%20in%20the%20right%0A%20%20-%20Magic%0A%0AMarkdown%20is%20a%20lightweight%20markup%20language%20based%20on%20the%20formatting%20conventions%20that%20people%20naturally%20use%20in%20email.%20%20As%20[John%20Gruber]%20writes%20on%20the%20[Markdown%20site]%20[1]%3A%0A%0A%3E%20The%20overriding%20design%20goal%20for%20Markdown%27s%0A%3E%20formatting%20syntax%20is%20to%20make%20it%20as%20readable%0A%3E%20as%20possible.%20The%20idea%20is%20that%20a%0A%3E%20Markdown-formatted%20document%20should%20be%0A%3E%20publishable%20as-is%2C%20as%20plain%20text%2C%20without%0A%3E%20looking%20like%20it%27s%20been%20marked%20up%20with%20tags%0A%3E%20or%20formatting%20instructions.%0A%0AThis%20text%20you%20see%20here%20is%20*actually*%20written%20in%20Markdown!%20To%20get%20a%20feel%20for%20Markdown%27s%20syntax%2C%20type%20some%20text%20into%20the%20left%20window%20and%20watch%20the%20results%20in%20the%20right.%0A%0A%23%23%23%20Version%0A3.0.0%0A%0A%23%23%23%20Tech%0A%0ADillinger%20uses%20a%20number%20of%20open%20source%20projects%20to%20work%20properly%3A%0A%0A*%20[AngularJS]%20-%20HTML%20enhanced%20for%20web%20apps!%0A*%20[Ace%20Editor]%20-%20awesome%20web-based%20text%20editor%0A*%20[Marked]%20-%20a%20super%20fast%20port%20of%20Markdown%20to%20JavaScript%0A*%20[Twitter%20Bootstrap]%20-%20great%20UI%20boilerplate%20for%20modern%20web%20apps%0A*%20[node.js]%20-%20evented%20I%2FO%20for%20the%20backend%0A*%20[Express]%20-%20fast%20node.js%20network%20app%20framework%20[%40tjholowaychuk]%0A*%20[Gulp]%20-%20the%20streaming%20build%20system%0A*%20[keymaster.js]%20-%20awesome%20keyboard%20handler%20lib%20by%20[%40thomasfuchs]%0A*%20[jQuery]%20-%20duh%0A%0A%23%23%23%20Installation%0A%0A%60%60%60sh%0A%24%20git%20clone%20[git-repo-url]%20dillinger%0A%24%20cd%20dillinger%0A%24%20npm%20i%20-d%0A%24%20mkdir%20-p%20public%2Ffiles%2F{md%2Chtml%2Cpdf}%0A%24%20gulp%20build%20--prod%0A%24%20NODE_ENV%3Dproduction%20node%20app%0A%60%60%60%0A%0A%23%23%23%20Plugins%0A%0ADillinger%20is%20currently%20extended%20with%20the%20following%20plugins%0A%0A*%20Dropbox%0A*%20Github%0A*%20Google%20Drive%0A*%20OneDrive%0A%0AReadmes%2C%20how%20to%20use%20them%20in%20your%20own%20application%20can%20be%20found%20here%3A%0A%0A*%20plugins%2Fdropbox%2FREADME.md%0A*%20plugins%2Fgithub%2FREADME.md%0A*%20plugins%2Fgoogledrive%2FREADME.md%0A*%20plugins%2Fonedrive%2FREADME.md%0A%0A%23%23%23%20Development%0A%0AWant%20to%20contribute%3F%20Great!%0A%0ADillinger%20uses%20Gulp%20%2B%20Webpack%20for%20fast%20developing.%0AMake%20a%20change%20in%20your%20file%20and%20instantanously%20see%20your%20updates!%0A%0AOpen%20your%20favorite%20Terminal%20and%20run%20these%20commands.%0A%0AFirst%20Tab%3A%0A%60%60%60sh%0A%24%20node%20app%0A%60%60%60%0A%0ASecond%20Tab%3A%0A%60%60%60sh%0A%24%20gulp%20watch%0A%60%60%60%0A%0A%28optional%29%20Third%3A%0A%60%60%60sh%0A%24%20karma%20start%0A%60%60%60%0A%0A%23%23%23%20Todo%27s%0A%0AWrite%20Tests%0AGithub%20saving%20overhaul%0ACode%20Commenting%0ANight%20Mode%0A%0ALicense%0A----%0A%0AMIT%0A%0A%0A**Free%20Software%2C%20Hell%20Yeah!**%0A%0A[john%20gruber]%3Ahttp%3A%2F%2Fdaringfireball.net%2F%0A[%40thomasfuchs]%3Ahttp%3A%2F%2Ftwitter.com%2Fthomasfuchs%0A[1]%3Ahttp%3A%2F%2Fdaringfireball.net%2Fprojects%2Fmarkdown%2F%0A[marked]%3Ahttps%3A%2F%2Fgithub.com%2Fchjj%2Fmarked%0A[Ace%20Editor]%3Ahttp%3A%2F%2Face.ajax.org%0A[node.js]%3Ahttp%3A%2F%2Fnodejs.org%0A[Twitter%20Bootstrap]%3Ahttp%3A%2F%2Ftwitter.github.com%2Fbootstrap%2F%0A[keymaster.js]%3Ahttps%3A%2F%2Fgithub.com%2Fmadrobby%2Fkeymaster%0A[jQuery]%3Ahttp%3A%2F%2Fjquery.com%0A[%40tjholowaychuk]%3Ahttp%3A%2F%2Ftwitter.com%2Ftjholowaychuk%0A[express]%3Ahttp%3A%2F%2Fexpressjs.com%0A[AngularJS]%3Ahttp%3A%2F%2Fangularjs.org%0A[Gulp]%3Ahttp%3A%2F%2Fgulpjs.com%0A&gistid=&theme=1).

**Comment by ethel-dev** [comment]
It looks like this is a problem with GitHub Pages or a limitation of URL parameters. Sorry, but at the moment I can't do anything about this :(
